### ISSUE TITLE
Installing issue with AUR/YaY and PIP

### ISSUE THREAD

**Issue by jparsert** [ManimCommunity/ManimPango#93]
When installing with either AUR or PIP I get an error that "glib.h" is not found gcc when compiling `cmanimpango.c`. Given that that seems to be a local header as it is included with "" rather than <> it seems almost if there is some dependency that is not packaged.

**Comment by naveen521kk** [comment]
> When installing with either AUR or PIP I get an error that "glib.h" is not found gcc when compiling cmanimpango.c

`glib.h` is provided by the `glib` package which Pango depends on, so if it fails with that error you probably didn't install that package. Follow https://github.com/ManimCommunity/ManimPango#linuxmacos or contact the AUR maintainer.

>  Given that that seems to be a local header as it is included with "" rather than <> it seems almost if there is some dependency that is not packaged.

My understanding of `<>` vs `""` is that the former is for headers provided by C-standard lib (and available in the standard include path) and the latter is for headers present in other directories. In this case, `glib.h` is provided by the glib package (and _not_ a standard library header) and its include directories are added to compiler flags, so that the compiler can find it.
